### ISSUE TITLE
App crashes when notifications are enabled

### ISSUE THREAD

**Issue by noerw** [sitcomlab/simport-learning-app#62]
..and a new point is incoming
*edit:* The notification is emitted nonetheless. Also the "background tracking stopped"-notification causes a crash.

On Android 8.1 (on a LG nexus 5x). Android API 29 in emulator is affected too.
I'll try to get a stacktrace soon
(Not only the latest version is affected)

**Comment by noerw** [comment]
```
--------- beginning of crash
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: FATAL EXCEPTION: main
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: Process: de.ifgi.simport.learning, PID: 15615
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View org.apache.cordova.CordovaWebViewEngine.getView()' on a null object reference
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at de.appplant.cordova.plugin.localnotification.LocalNotification$2.run(LocalNotification.java:721)
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-13 12:05:05.848 10146 15615 15615 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.NullPointerException: Attempt to invoke interface method 'android.view.View org.apache.cordova.CordovaWebViewEngine.getView()' on a null object reference
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at de.appplant.cordova.plugin.localnotification.LocalNotification$2.run(LocalNotification.java:721)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Handler.handleCallback(Handler.java:790)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:164)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-13 12:05:05.854 10146 15615 15615 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-13 12:05:05.899  1000   766 17557 W ActivityManager:   Force finishing activity de.ifgi.simport.learning/.MainActivity
04-13 12:05:05.912 10040  1636  1636 I chatty  : uid=10040(com.android.systemui) expire 5 lines
04-13 12:05:05.926  1000   766   783 I ActivityManager: Showing crash dialog for package de.ifgi.simport.learning u0
```

Looks like a bug in the LocalNotification dependency?
However we didn't trigger the broken codepath in the past.. hm.

**Comment by noerw** [comment]
@felixerdy What android version does the device run, where you couldn't reproduce this issue?

**Comment by noerw** [comment]
I'm starting to believe that this is caused by a broken build environment on my side, as the builds from the "Android-Distribution" CI task do not cause this issue.

The null exception is caused, because on the broken builds, the `view` variable in `android/capacitor-cordova-android-plugins/src/main/java/de/appplant/cordova/plugin/localnotification/LocalNotification.java` line 716 is an instance of `MockCordovaWebViewImpl`, which does not implement the `getEngine()` call properly:

https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java#L237

Could someone set a breakpoint in line 716 in `LocalNotification.java` and check what class `view` has in their local build?

**Comment by schrooom** [comment]
> Could someone set a breakpoint in line 716 in `LocalNotification.java` and check what class `view` has in their local build?

I've just tested the current develop-branch on a device with android 9: it does indeed crash pretty much everytime for me too - with the view being a `com.getcapacitor.cordova.MockCordovaWebViewImpl`.

Update and another confirmation: Builds from Android-Distribution CI task do not cause this issue.

**Comment by felixerdy** [comment]
I'm using OnePlus 3T with Android 9 (stock). I am able to start location tracking with notifications enabled which are not crashing the app. Also, the "background tracking stopped" notification is working flawlessly on my device. Just did a fresh installation of the app trough the firebase App Tester and still everything is working. I did not take a look at the Logcat yet but there are no issues on user side in my case.

EDIT: Just checked the Logcat, nothing to worry about

<details>
  <summary>Logcat on location receive with notifications and app running in foreground</summary>
  
 ```
2021-04-16 14:22:04.830 25249-25395/? V/Capacitor/Plugin: To native (Cordova plugin): callbackId: LocalNotification1010439830, service: LocalNotification, action: request, actionArgs: []
2021-04-16 14:22:04.870 25249-25249/? W/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 88077 - Msg: Native: tried calling BackgroundGeolocation.finish, but the BackgroundGeolocation plugin is not installed.
2021-04-16 14:22:04.871 25249-25249/? W/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 88083 - Msg: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add @mauron85/cordova-plugin-background-geolocation'
2021-04-16 14:22:04.872 25249-25395/? V/Capacitor/Plugin: To native (Cordova plugin): callbackId: INVALID, service: LocalNotification, action: schedule, actionArgs: [{"id":656804.315638668,"text":"Received location update 51.xxxxxx 7.xxxxx 14.42300033569336","data":"{}","actions":[],"alarmVolume":-1,"attachments":[],"autoLaunch":false,"autoClear":true,"clock":true,"defaults":0,"groupSummary":false,"launch":true,"led":true,"lockscreen":true,"number":0,"priority":0,"progressBar":{"enabled":false,"value":0,"maxValue":100,"indeterminate":false},"resetDelay":5,"silent":false,"smallIcon":"res:\/\/icon","sound":true,"timeoutAfter":null,"title":"","trigger":{"type":"calendar"},"vibrate":false,"wakeup":true,"fullScreenIntent":false,"triggerInApp":false,"meta":{"plugin":"cordova-plugin-local-notification","version":"0.9-beta.4"}}]
2021-04-16 14:22:04.873 25249-5099/? D/local-notification: Next trigger at: Fri Apr 16 14:22:04 GMT+02:00 2021
2021-04-16 14:22:05.007 20172-20172/? D/NotificationListener: onNotificationPosted# hash: 73422595 sbn: StatusBarNotification(pkg=de.ifgi.simport.learning user=UserHandle{0} id=656804 tag=null key=0|de.ifgi.simport.learning|656804|null|10252: Notification(channel=sound-channel-id pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0x00000000 vis=PUBLIC))
2021-04-16 14:22:05.014 20172-20172/? D/NotificationListener: onNotificationRankingUpdate# hash: 73422595 rankingMap: android.service.notification.NotificationListenerService$RankingMap@7c190ee
2021-04-16 14:22:05.024 20172-20172/? D/NotificationListener: onNotificationRankingUpdate# hash: 73422595 rankingMap: android.service.notification.NotificationListenerService$RankingMap@da7698f
2021-04-16 14:22:05.027 3361-3361/? D/NotificationEntryMgr: No peeking: unimportant notification: 0|de.ifgi.simport.learning|656804|null|10252
2021-04-16 14:22:05.188 3361-5106/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:22:05.191 3361-5106/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:22:05.210 3361-3361/? D/NotificationEntryMgr: No peeking: unimportant notification: 0|de.ifgi.simport.learning|656804|null|10252
2021-04-16 14:22:05.213 3361-3361/? D/NotificationEntryMgr: No peeking: unimportant notification: 0|de.ifgi.simport.learning|656804|null|10252
2021-04-16 14:22:05.236 3361-3361/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:22:05.251 3361-3361/? I/chatty: uid=10009(com.android.systemui) identical 2 lines
2021-04-16 14:22:05.253 3361-3361/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:22:05.259 3361-3361/? D/StatusBar: updateMediaMetaData: hasArtwork = true, mState:0, false, mDozing:false, delay:0, true, vis:8, alpha:0.0019999743, false, meta:false, fading:false, 0, false
2021-04-16 14:22:05.265 3361-3361/? W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
2021-04-16 14:22:05.497 2497-5131/? D/VibratorService: vibrate from 'de.ifgi.simport.learning', usageHint = 5
2021-04-16 14:22:05.503 2497-5131/? D/VibratorService: startTime: 16.04.2021, 14:22:05, effect: Waveform{mTimings=[0, 100, 150, 100], mAmplitudes=[0, 255, 0, 255], mRepeat=-1}, originalEffect: Waveform{mTimings=[0, 100, 150, 100], mAmplitudes=[0, -1, 0, -1], mRepeat=-1}, usageHint: 5, uid: 10252, opPkg: de.ifgi.simport.learning
2021-04-16 14:22:05.267 3361-3361/? I/chatty: uid=10009(com.android.systemui) identical 1 line
2021-04-16 14:22:05.268 3361-3361/? W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
2021-04-16 14:22:05.539 20172-20172/? D/NotificationListener: onNotificationRemoved# hash: 73422595 sbn: StatusBarNotification(pkg=android user=UserHandle{-1} id=84672560 tag=null key=-1|android|84672560|null|1000: Notification(channel=OP_GPS_NOTIFICATION pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x2 color=0xff607d8b vis=PUBLIC))
2021-04-16 14:22:05.543 3361-3361/? D/StatusBar: updateMediaMetaData: hasArtwork = true, mState:0, false, mDozing:false, delay:0, true, vis:8, alpha:0.0019999743, false, meta:false, fading:false, 0, false
```
</details>

<details>
  <summary>Logcat on location receive with notifications and app running in background</summary>
  
```
2021-04-16 14:27:27.160 25249-25395/? V/Capacitor/Plugin: To native (Cordova plugin): callbackId: LocalNotification1010439836, service: LocalNotification, action: request, actionArgs: []
2021-04-16 14:27:27.198 25249-25249/? W/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 88077 - Msg: Native: tried calling BackgroundGeolocation.finish, but the BackgroundGeolocation plugin is not installed.
2021-04-16 14:27:27.199 25249-25249/? W/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 88083 - Msg: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add @mauron85/cordova-plugin-background-geolocation'
2021-04-16 14:27:27.199 25249-25395/? V/Capacitor/Plugin: To native (Cordova plugin): callbackId: INVALID, service: LocalNotification, action: schedule, actionArgs: [{"id":460178.5887444436,"text":"Received location update 51.xxxxxx 7.xxxxxx 15.442000389099121","data":"{}","actions":[],"alarmVolume":-1,"attachments":[],"autoLaunch":false,"autoClear":true,"clock":true,"defaults":0,"groupSummary":false,"launch":true,"led":true,"lockscreen":true,"number":0,"priority":0,"progressBar":{"enabled":false,"value":0,"maxValue":100,"indeterminate":false},"resetDelay":5,"silent":false,"smallIcon":"res:\/\/icon","sound":true,"timeoutAfter":null,"title":"","trigger":{"type":"calendar"},"vibrate":false,"wakeup":true,"fullScreenIntent":false,"triggerInApp":false,"meta":{"plugin":"cordova-plugin-local-notification","version":"0.9-beta.4"}}]
2021-04-16 14:27:27.200 25249-5490/? D/local-notification: Next trigger at: Fri Apr 16 14:27:27 GMT+02:00 2021
2021-04-16 14:27:27.205 2497-2728/? I/DisplayPowerController: useProximityForceSuspend = false
2021-04-16 14:27:27.205 2497-2728/? D/RestartProcessManager: Screen off is false
2021-04-16 14:27:27.331 20172-20172/? D/NotificationListener: onNotificationPosted# hash: 73422595 sbn: StatusBarNotification(pkg=de.ifgi.simport.learning user=UserHandle{0} id=460178 tag=null key=0|de.ifgi.simport.learning|460178|null|10252: Notification(channel=sound-channel-id pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0x00000000 vis=PUBLIC))
2021-04-16 14:27:27.337 3361-3361/? D/NotificationEntryMgr: No peeking: unimportant notification: 0|de.ifgi.simport.learning|460178|null|10252
2021-04-16 14:27:27.400 3361-5543/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.404 3361-5543/? I/chatty: uid=10009(com.android.systemui) InflaterThread identical 1 line
2021-04-16 14:27:27.404 3361-5543/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.407 3361-5541/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.407 3361-5543/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.408 3361-5544/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.427 3361-3361/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.433 3361-3361/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.439 3361-5543/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.439 3361-5543/? E/ndroid.systemu: Invalid ID 0x00000000.
2021-04-16 14:27:27.445 3361-3361/? D/NotificationEntryMgr: No peeking: unimportant notification: 0|de.ifgi.simport.learning|460178|null|10252
2021-04-16 14:27:27.446 3361-3361/? D/NotificationEntryMgr: No peeking: unimportant notification: 0|de.ifgi.simport.learning|460178|null|10252
2021-04-16 14:27:27.453 3361-3361/? D/StatusBar: updateMediaMetaData: hasArtwork = true, mState:0, false, mDozing:false, delay:0, true, vis:8, alpha:0.002000004, false, meta:false, fading:false, 0, false
2021-04-16 14:27:27.461 3361-3361/? W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
2021-04-16 14:27:27.827 2497-5539/? D/VibratorService: vibrate from 'de.ifgi.simport.learning', usageHint = 5
2021-04-16 14:27:27.830 2497-2728/? I/DisplayPowerController: useProximityForceSuspend = false
2021-04-16 14:27:27.831 2497-2728/? D/RestartProcessManager: Screen off is false
2021-04-16 14:27:27.833 2497-5539/? D/VibratorService: startTime: 16.04.2021, 14:27:27, effect: Waveform{mTimings=[0, 100, 150, 100], mAmplitudes=[0, 255, 0, 255], mRepeat=-1}, originalEffect: Waveform{mTimings=[0, 100, 150, 100], mAmplitudes=[0, -1, 0, -1], mRepeat=-1}, usageHint: 5, uid: 10252, opPkg: de.ifgi.simport.learning
2021-04-16 14:27:27.462 3361-3361/? I/chatty: uid=10009(com.android.systemui) identical 1 line
2021-04-16 14:27:27.462 3361-3361/? W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
2021-04-16 14:27:27.875 20172-20172/? D/NotificationListener: onNotificationRemoved# hash: 73422595 sbn: StatusBarNotification(pkg=android user=UserHandle{-1} id=84672560 tag=null key=-1|android|84672560|null|1000: Notification(channel=OP_GPS_NOTIFICATION pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x2 color=0xff607d8b vis=PUBLIC))
2021-04-16 14:27:27.889 3361-3361/? D/StatusBar: updateMediaMetaData: hasArtwork = true, mState:0, false, mDozing:false, delay:0, true, vis:8, alpha:0.002000004, false, meta:false, fading:false, 0, false
```

</details>



However, after some time the app stops to record new location points even tough the "Background tracking ENABLED" is still present. Maybe the battery saver stuff on my device is causing that behaviour, but thats a new issue nevertheless.

**Comment by noerw** [comment]
This was caused by a missing run of "Sync Project with Grade Files" in android studio.
After executing that, builds don't have this issue anymore.

**Comment by schrooom** [comment]
> This was caused by a missing run of "Sync Project with Grade Files" in android studio.
> After executing that, builds don't have this issue anymore.

Unfortunately this does not do it for me - still the same behavior after syncing grade files. Should we address this further, since the distributed builds are fine?

**Comment by noerw** [comment]
Yeah, I think that's what we've settled on.
You can also try to run `ionic cap update` before the gradle sync, maybe that fixed it for me

**Comment by felixerdy** [comment]
This issue just reappeared after the toolchain update #84. I'm having the same issue on my local machine now. Any ideas or hints what needs to be done @noerw?  "Sync Project with Grade Files" or `ionic cap update` didn't work for me.
